### ISSUE TITLE

        docs: added conditional slots section in slots guide
    

### ISSUE THREAD

**Issue by cs-vuejs-org** [vuejs-translations/docs-cs#128]
New updates on head repo.
https://github.com/vuejs/docs/commit/1ab62a56370fe957a960d71a3cc40f1e248d163c

**Comment by AloisSeckar** [comment]
ported in cb0e973b0497deed7091e5a27d546228edf454dd

(together with fixes introduced in https://github.com/vuejs/docs/pull/2780)
