### ISSUE TITLE
Traslate /ecosystem/themes/themes.json

### ISSUE THREAD

**Issue by AloisSeckar** [vuejs-translations/docs-cs#17]
[`/ecosystem/themes/themes.json`](https://github.com/vuejs-translations/docs-cs/blob/main/src/ecosystem/themes/themes.json) don't have `"description"` values translated yet.

I checked some translations do translate those, while others leave the English descriptions. Is there a recommendation?

**Comment by Jinjiang** [comment]
I personally think it's quite marketing thing for our partners, which are not considered a simple translation job. So I would prefer keeping the English versions as they are.

BTW, like Vue regional special sponsors, it could be up to our partners to decide whether they would like a different description or even link/brand/image in a translation doc site.

**Comment by AloisSeckar** [comment]
Not to be translated
