### ISSUE TITLE

        fix: add missing anchors on watchers and render-function
    

### ISSUE THREAD

**Issue by cs-vuejs-org** [vuejs-translations/docs-cs#18]
New updates on head repo.
https://github.com/vuejs/docs/commit/a4c52b92949bad0b259a33999ff510327c5df247

**Comment by AloisSeckar** [comment]
implemented in [d1a2aa2](https://github.com/vuejs-translations/docs-cs/commit/d1a2aa207185d90e86ce2ddc86aca0a0a68deece)
