### ISSUE TITLE

        add more details for watcher flush timing
    

### ISSUE THREAD

**Issue by cs-vuejs-org** [vuejs-translations/docs-cs#20]
New updates on head repo.
https://github.com/vuejs/docs/commit/80e2128d52603856a26a8bb7258606cfe80561e9

**Comment by AloisSeckar** [comment]
implemented in [0378fd3](https://github.com/vuejs-translations/docs-cs/commit/0378fd3eee44a2a1faa06acc4663a0135c209fe4)
