### ISSUE TITLE

        docs: add explanation for scoped slots with render functions
    

### ISSUE THREAD

**Issue by cs-vuejs-org** [vuejs-translations/docs-cs#21]
New updates on head repo.
https://github.com/vuejs/docs/commit/0a3f14471ddf1a884e48c188dd80e020a80eb4eb

**Comment by AloisSeckar** [comment]
implemented in [52136ba](https://github.com/vuejs-translations/docs-cs/commit/52136ba77c3a5f5dcac44828d553d077c7086e8e)
