### ISSUE TITLE

        Revert "add vueconf.us banner"
    

### ISSUE THREAD

**Issue by cs-vuejs-org** [vuejs-translations/docs-cs#251]
New updates on head repo.
https://github.com/vuejs/docs/commit/082ec4c47ed7d4cde91bba72b16d861bd58a321e

**Comment by AloisSeckar** [comment]
ported in f52b6d6add9094f9d5c2c3c6167ad17cf2fdbc96 && 034a38e1c5e723d629545102aeccbd63a66c71c7
