### ISSUE TITLE

        style: update event-handling.md avoid horizontal scrolling
    

### ISSUE THREAD

**Issue by cs-vuejs-org** [vuejs-translations/docs-cs#27]
New updates on head repo.
https://github.com/vuejs/docs/commit/7af19613ab0f6375cfe6dcf4b56e601ed39c3675

**Comment by AloisSeckar** [comment]
implemented in [f36c362](https://github.com/vuejs-translations/docs-cs/commit/f36c36290a3ada0c2a4165435db7a737d87f219a)
