### ISSUE TITLE

        Update slots.md link to Dynamic Argument Syntax Constraints
    

### ISSUE THREAD

**Issue by cs-vuejs-org** [vuejs-translations/docs-cs#33]
New updates on head repo.
https://github.com/vuejs/docs/commit/d7a77fe89264d0cc5e8cf10b4ff8ed8190349a85

**Comment by AloisSeckar** [comment]
Ported in [b2c384f](https://github.com/vuejs-translations/docs-cs/commit/b2c384f37d1bc1427ce1d26d6bffe3ec2c3635cb)
