### ISSUE TITLE

        chore(deps): bump vue from 3.5.0-beta.2 to 3.5.0-rc.1
    

### ISSUE THREAD

**Issue by cs-vuejs-org** [vuejs-translations/docs-cs#340]
New updates on head repo.
https://github.com/vuejs/docs/commit/c69984f021bf024c9e768eaa1f9a290b7d48520e

**Comment by AloisSeckar** [comment]
overwritten with b158ac8c97a1bf3d8e5fd214fe5d6f6ff223325e
