### ISSUE TITLE

        update `create vue` box
    

### ISSUE THREAD

**Issue by cs-vuejs-org** [vuejs-translations/docs-cs#41]
New updates on head repo.
https://github.com/vuejs/docs/commit/1ccf98c7bf7f4acd8b47713b6c57020e16c8b7d3

**Comment by AloisSeckar** [comment]
ported in [bc82ac8](https://github.com/vuejs-translations/docs-cs/commit/bc82ac8442980d522720ca3a01bfe64f074ad4fc)
