### ISSUE TITLE

        Corrected and improved docs on type definitions for Custom Elements. …
    

### ISSUE THREAD

**Issue by cs-vuejs-org** [vuejs-translations/docs-cs#428]
New updates on head repo.
https://github.com/vuejs/docs/commit/1cea4314f762939ab2c52ecfb20cafb6eb40e16d

**Comment by AloisSeckar** [comment]
I have this WIP, but since the update is bigger, I need more time to finish the translation

**Comment by AloisSeckar** [comment]
ported in 284fadf24a72eed536391f84a8daefce9f63fcfa
