### ISSUE TITLE

        fix(docs): typo in docs
    

### ISSUE THREAD

**Issue by cs-vuejs-org** [vuejs-translations/docs-cs#62]
New updates on head repo.
https://github.com/vuejs/docs/commit/8323f25189416c3dfcc8c20fac091fc0cd8ef22e

**Comment by AloisSeckar** [comment]
[cf792b6](https://github.com/vuejs-translations/docs-cs/commit/cf792b6658735d061d8246ff7f54e65a68cfa8c2)
