### ISSUE TITLE

        docs: remove takeover mode related docs
    

### ISSUE THREAD

**Issue by cs-vuejs-org** [vuejs-translations/docs-cs#63]
New updates on head repo.
https://github.com/vuejs/docs/commit/ca46758aab4233b7671a7eba049e10112ae23513

**Comment by AloisSeckar** [comment]
ported in [cf792b6](https://github.com/vuejs-translations/docs-cs/commit/cf792b6658735d061d8246ff7f54e65a68cfa8c2)
