### ISSUE TITLE

        docs: adjust punctuation in /src/guide/built-ins/transition.md
    

### ISSUE THREAD

**Issue by cs-vuejs-org** [vuejs-translations/docs-cs#98]
New updates on head repo.
https://github.com/vuejs/docs/commit/5f1a96fa6b052604e0032a2b4b487f2d2402f288

**Comment by AloisSeckar** [comment]
one ported in 6efd0122c2f80a66fbb052d4bba47e00cbc67e16
second already fixed during translation
